name: fluttergym
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1
environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rounded_progress_bar: "^0.1.2"
  bezier_chart: "^1.0.6"
  percent_indicator: "^2.1.1"
  cupertino_icons: ^0.1.2
  provider: ^3.2.0
  shared_preferences: ^0.5.6+1
  image_picker: ^0.6.3+1
  image_cropper: ^1.2.1
  loading_indicator: ^1.1.0
  http: ^0.12.0+4
  cloud_firestore: ^0.13.0+1
  firebase_core: ^0.4.0+9
  google_sign_in: ^4.1.1
  toast: ^0.1.5
  firebase_auth: ^0.15.4
  video_player: ^0.10.7
  firebase_storage: ^3.0.3
  flutter_facebook_login: ^3.0.0
  html: ^0.14.0+3
  geolocator: ^5.3.0
  dotted_border: ^1.0.4
  chewie: ^0.9.8+1
  dots_indicator: ^1.1.0
  url_launcher: ^5.4.1
  unicorndial: ^1.1.5
  flutter_zoom_drawer: ^1.0.4
  awesome_dialog: ^1.2.0


  #video_thumbnail: ^0.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec


# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  fonts:
    - family: Geometria
      fonts:
        - asset: fonts/Geometria-Bold.ttf
        - asset: fonts/Geometria-ExtraBold.ttf
          weight: 700
  assets:
    - assets/images/